### ISSUE TITLE
ImportError: cannot import name 'DataClass' from 'commlib.msg'

### ISSUE THREAD

**Issue by mcarlos137** [robotics-4-all/commlib-py#33]
I am trying to create a RPC just like example: 

class AddTwoIntMessage(RPCMessage):
    @DataClass
    class Request(RPCMessage.Request):
        a: int = 0
        b: int = 0

    @DataClass
    class Response(RPCMessage.Response):
        c: int = 0
....

but I just did this without @DataClass:

class AddTwoIntMessage(RPCMessage):
    class Request(RPCMessage.Request):
        a: int = 0
        b: int = 0

    class Response(RPCMessage.Response):
        c: int = 0

That calls the RPC but there is no way to see the response.

Is there another way to update the response?

**Comment by klpanagi** [comment]
Hello @mcarlos137 
Sorry, I have left that [README](https://github.com/robotics-4-all/commlib-py/blob/master/examples/simple_rpc/README.md) outdated and will be removed in the future.

The latest changes introduced new features and a new way of defining communication messages.

The main [README](https://github.com/robotics-4-all/commlib-py/blob/master/README.md) is also outdated. I will update that within the week.

Please look at the example source code for now [here](https://github.com/robotics-4-all/commlib-py/blob/master/examples/simple_rpc/simple_rpc_service.py#L9)

**Comment by klpanagi** [comment]
> That calls the RPC but there is no way to see the response.

> Is there another way to update the response?

How do you make the RPC call? Please provide the source code

**Comment by mcarlos137** [comment]
class Handler(FileSystemEventHandler):

    @staticmethod
    def on_any_event(event):
        if event.is_directory:
            return None

        elif event.event_type == 'created':
            # Take any action here when a file is first created.
            print("Received created event - %s." % event.src_path)

        elif event.event_type == 'modified':
            # Taken any action here when a file is modified.
            print("Received modified event - %s." % event.src_path)
            request = json.loads(open(event.src_path, 'r').read())
            instance_id = request['instance_id']
            action = request['action']
            print(f'instance_id: {instance_id}')
            print(f'action: {action}')
            conn_params = ConnectionParameters(
                host='localhost', port=1883, username='mqtt-test', password='mqtt-test')
            node = Node(node_name='broker',
                        connection_params=conn_params,
                        # heartbeat_uri='nodes.add_two_ints.heartbeat',
                        debug=True)
            rpc = node.create_rpc_client(msg_type=RPCCMessage,
                                         rpc_name=f'hbot/{instance_id}/{action}')
            node.run()
            msg = RPCCMessage.Request()
            msg.request = '{}'
            resp = rpc.call(msg)
            while True:
                # returns AddTwoIntMessage.Response instance
                print(resp) #######Always receives None########
                time.sleep(1)
                
class RPCCMessage(RPCMessage):
    class Request(RPCMessage.Request):
        request: str = ''

    class Response(RPCMessage.Response):
        data: dict = None

**Comment by mcarlos137** [comment]
I send: 

commlib-cli --username mqtt-test --password mqtt-test --host localhost --port 1883 --btype mqtt rpcc 'hbot/78b7d9e5ac70d6e87bab1f3c436dfa5372fcbfcb/status' '{}'

I receive:

{'status': 400, 'msg': 'No strategy is currently running!', 'data': ''}  ###This is the response I need for my case

**Comment by klpanagi** [comment]
@mcarlos137 did you resolve the issue?

Sorry I was AFK for some days.

In your case, it seems that you get a timeout from the RPC call, that is the reason you get `None` as a response.

Reasons for this are:

- Connection failure with the MQTT broker
- No RPC service listens to the topic, thus causing a timeout on client side while waiting for response.
