### ISSUE TITLE
Request for a new repo release to align conda-recipe

### ISSUE THREAD

**Issue by MementoRC** [robotics-4-all/commlib-py#41]
@klpanagi , Do you think you will make a new release in the repo. The pypi package has v0.10.7, but your release is v0.10.6. My conda recipes are starting to get reviewed and it would be great if I could update the recipe with the latest verion that you deem stable
Thanks

**Comment by MementoRC** [comment]
@klpanagi I just realized that there is a pypi v0.11.1, but your latest release is 0.10.6. The reviewer is asking to use the release tag (instead of a commit), so to have the latest version I would have to use the Pypi package

**Comment by klpanagi** [comment]
Hello @MementoRC . Sorry I was AFK some time.
I have aligned both to `0.11.2` lately.
Can you verify?

**Comment by MementoRC** [comment]
Cool @klpanagi , works much better
